services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest

    ports:
      - "4566:4566"

    environment:
      LOCALSTACK_AUTH_TOKEN: ls-GUYO5254-5923-JajA-QExO-zudaXOcUb48c
      DEBUG: "1"
      PERSISTENCE: "1"

    volumes:
      - localstack_data:/var/lib/localstack
      - "//var/run/docker.sock:/var/run/docker.sock"

volumes:
  localstack_data: